### ISSUE TITLE
Update to Python3.x

### ISSUE THREAD

**Issue by ChristianVaughn** [opiumozor/spotify-cover-downloader#3]
Could you possibly update this to a Python 3.x version and fix the requirements.txt. Python 2 is no longer supported by python team, and The requirements.txt gives an error when trying to run with pip3
`ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)`

**Comment by mfn003** [comment]
You're installing the dependencies wrong. You need to use `pip3 install -r requirements.txt`

**Comment by ChristianVaughn** [comment]
> You're installing the dependencies wrong. You need to use `pip3 install -r requirements.txt`

First off i was trying to install stuff right and i said i was using pip3.
Also this code doesn't actually work with Python 3.x there are functions in the code whos formating have changed from python2 to 3

**Comment by mfn003** [comment]
You were very clearly installing the dependencies wrong: https://pip.pypa.io/en/stable/getting-started/#install-multiple-packages-using-a-requirements-file

And for the Python 2 part, fair enough, but the dependency install doesn't involve this
